name: CI

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn
        run: yarn install --silent
      - name: ESLint
        run: yarn run eslint
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn
        run: yarn install --silent
      - name: TypeScript
        run: yarn run typescript:check
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn
        run: yarn install --silent
      - name: Jest
        run: yarn run test
